45 tab bar component
GSG-G13/trakio pull request #57
Opened 2023-07-01 18:12 UTC by KhaledToha

2023-07-01 18:17 UTC, Amal-Mousa approved these changes

2023-07-01 20:09 UTC, nada-abuzaid requested changes

2023-07-01 20:09 UTC, nada-abuzaid commented on src/components/TaskTabBar/index.tsx
> +                  <Typography color={THEME.palette.custom.gray} fontSize={13}>{tab}</Typography>
please mark the selected tap! "active tap" See [more](https://reactrouter.com/en/main/components/nav-link#children)

```suggestion
{({ isActive }) => (
       <Typography
           color={isActive ? 'custom.white' : 'custom.gray'}
           fontSize={13}
           fontWeight={isActive ? 'bold' : 'normal'}>
          {tab}
         </Typography>
    )}
```

2023-07-01 20:09 UTC, nada-abuzaid commented on src/components/TaskTabBar/index.tsx
> +              {tabs.map((tab, index) => (
"لما ترفعوا يا جماعة شوفوا الconsole بليز" -بصوت أحدهم- 😈

<img width="715" alt="image" src="https://github.com/GSG-G13/trakio/assets/52599778/f72879c4-2ca5-4def-b433-677a5119b07f">

2023-07-01 20:09 UTC, nada-abuzaid commented on src/components/ProjectTabBar/index.tsx
I think we can handle the `TaskTabBar` and use it here instead of duplicate the code

2023-07-01 20:09 UTC, nada-abuzaid commented on src/components/Layout/index.tsx
> +      {/* <PermanentAppBar /> */}
Commented Code! 😈

2023-07-01 20:09 UTC, nada-abuzaid commented on src/components/Layout/index.tsx
> +  const location = useLocation();
```suggestion
  const { pathname }  = useLocation();
```

2023-07-02 07:10 UTC, nada-abuzaid approved these changes

2023-07-02 07:13 UTC, AyaAljalees approved these changes

2023-07-02 07:14 UTC, Mohammed-Sbeata approved these changes
Good Job 👏

2023-07-02 07:15 UTC, merged