Edit sidebar
GSG-G13/trakio pull request #68
Opened 2023-07-02 19:23 UTC by Amal-Mousa

2023-07-02 22:29 UTC, nada-abuzaid requested changes

2023-07-02 22:29 UTC, nada-abuzaid commented on src/components/Sidebar/index.tsx
>                <NavLink to={`/project/${project.project_id}`} style={{ textDecoration: 'none' }}>
remove the NavLink and set the path into list item button directly!

2023-07-02 22:29 UTC, nada-abuzaid commented on src/components/Sidebar/index.tsx
> +              p: 1, display: 'flex', flexDirection: 'column', gap: '0.8rem',
```suggestion
              p: 1, display: 'flex', flexDirection: 'column', gap: '0.6rem',
```

2023-07-02 22:29 UTC, nada-abuzaid commented on src/components/Sidebar/index.tsx
> +              <Typography sx={{ color: 'custom.white', fontSize: '18px' }}>
```suggestion
              <Typography sx={{ color: 'custom.fontGray', fontSize: '16px' }}>
```

2023-07-02 22:29 UTC, nada-abuzaid commented on src/components/Sidebar/index.tsx
> +          <Box sx={{ px: 2.5, py: 3, display: 'inline-flex' }}>
```suggestion
          <Box sx={{ px: 2.5, py: 2, display: 'inline-flex' }}>
```

2023-07-02 22:29 UTC, nada-abuzaid commented on src/components/Sidebar/index.tsx
>  // import PermanentAppBar from '../AppBar';
remove it

2023-07-02 22:29 UTC, nada-abuzaid commented on src/components/Signup/index.tsx
> +import ReactLogo from '../../../public/assets/logo.svg';
```suggestion
import ReactLogo from '/assets/logo.svg';
```

2023-07-02 22:29 UTC, nada-abuzaid commented on src/components/WelcomeCard/index.tsx
> +import myImage from '../../../public/assets/welcome.svg';
```suggestion
import myImage from '/assets/welcome.svg';
```

2023-07-02 22:29 UTC, nada-abuzaid commented on src/fake.ts
> +  photoURL: '../public/assets/avatars/avatar_default.jpg',
```suggestion
  photoURL: '/assets/avatars/avatar_default.jpg',
```

2023-07-02 22:29 UTC, nada-abuzaid commented on src/components/Common/ListItem.tsx
> +        <MdDashboard style={{ fontSize: 22, color: 'custom.white' }} />
```suggestion
        <MdDashboard style={{ fontSize: 18, color: 'custom.white' }} />
```

2023-07-02 22:29 UTC, nada-abuzaid commented on src/components/Login/index.tsx
in the `src/components/Login/LoginForm/index.tsx`
line 121:
```JS
          <LoginImage src="/assets/todo.svg" alt="login" />
```

2023-07-03 06:53 UTC, nada-abuzaid approved these changes

2023-07-03 06:54 UTC, Mohammed-Sbeata approved these changes
BRAVOOOO NADA
👏👏👏👏

2023-07-03 06:55 UTC, KhaledToha approved these changes

2023-07-03 06:55 UTC, merged